name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Add GitHuB souce package
      run: dotnet nuget add source https://nuget.pkg.github.com/beritcarvalho/index.json --name github -u beritcarvalho -p ${{ secrets.GIT_TOKEN_PACKAGE }} --store-password-in-clear-text

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Publish nuget
      run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.GIT_TOKEN_PACKAGE }} --source "https://nuget.pkg.github.com/beritcarvalho/index.json"